#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Emacs state=tiled
#AutoStart
picom &
feh --bg-scale /home/rad/Downloads/painting-mountain-lake-with-mountain-background.jpg
$HOME/.config/polybar/launch.sh --shapes

